### ISSUE TITLE
Add support to path prefixes

### ISSUE THREAD

**Issue by pracucci** [fatih/faillint#12]
We have some use cases where we would like to blacklist an import path prefix so that all import packages belonging to that prefix are blacklisted as well. Would be of any interest to add such feature to the project?

**Comment by fatih** [comment]
Yeah we need something like this indeed. There was an open PR that was supposed to implement it: https://github.com/fatih/faillint/pull/2 however because we merged other changes, it has now some conflicts that needs to be resolved.

We also need to decide on how to define the syntax.Even though #2 is implementing this feature, the assumption that if you have an import path in the form of: `foo/bar/qux` and you want to import `foo` and all other packages, you just write `foo`. But the problem with this issue is, there is no way to tell: don't allow `foo`, but allow `foo/bar` or `foo/bar/qux`. 

Maybe we add a special char `*` to indicate that it also blocks all sub package, such as `foo/*.

**Comment by pracucci** [comment]
I agree that this shouldn't break any other functionality we already have. I was thinking about two options:

1. `foo/*`
2. `foo/...`

**Comment by fatih** [comment]
I started working on this using the `foo/...` syntax as I think it's clearer and also looks similiar to the syntax used in go commands (i.e: `go test ./...`). 

I'll update the issue once I have something working. Note that I couldn't continue using #2 anymore as we significantly changed how parse the paths.
