### ISSUE TITLE
[Feature Request] Autofix support

### ISSUE THREAD

**Issue by magodo** [fatih/faillint#19]
Rather than printing a warning and a suggestion, it should be possible to allow user to specify an option (e.g. `-fix`) so that directly replace the offending import path with the suggested one.

**Comment by fatih** [comment]
Hi @magodo 

It would be nice to have it, but I'm not sure autofix is a good choice for this particular linter. We don't want to fix things if we don't know what the replacement is. That's very difficult to know and it depends on the user's choice. I'll close this because this feature request is something I'm not interested (for now)
